### ISSUE TITLE
Make ParseDhcpOffer work without a DNS address

### ISSUE THREAD

**Issue by ghost** [minexew/Shrine#15]
Currently, if `ParseDhcpOffer` receives a DHCP offer that doesn't contain a DNS option, it fails. However, this makes testing Shrine within a VirtualBox host network (which doesn't have a DNS server) impossible, because the address resolution will consistently fail.

Because of that, `ParseDhcpOffer` should be made to accept DNS-less DHCP offers, as a DNS isn't required for normal operation of Shrine (from what I've seen at least).

**Comment by minexew** [comment]
The specific check that rejects DNS-less DHCP offers is at https://github.com/minexew/Shrine/blob/4465412cda517399c2487785e3f4a9a2ebe77e2d/SnailNet/Dhcp.HC#L245

It seems that Dns.HC is prepared for the possibility of not having a valid DNS server. (https://github.com/minexew/Shrine/blob/4465412cda517399c2487785e3f4a9a2ebe77e2d/SnailNet/Dns.HC#L136) The -1 return value should be replaced with a proper error code if it is actually propagated.

I am unsure if/how it should be communicated by DhcpParseOffer that the DHCP request was satisfied, but no DNS was provided.

If you can implement and test the necessary changes, I would gladly merge them.

**Comment by tuxcrafting** [comment]
Sure. I also found that the VirtualBox DHCP server on host networks doesn't send a ROUTER type message (probably because a gateway is not needed considering host networks are local only).

From what I understand a null gateway address will simply cause an invalid address error on addresses outside of the subnet [https://github.com/minexew/Shrine/blob/master/SnailNet/IPv4.HC#L91, https://github.com/minexew/Shrine/blob/master/SnailNet/IPv4.HC#L79], which should work as an error.

As such, the changes to do seem to just be removing the `have_dns` and `have_router` checks.

**Comment by tuxcrafting** [comment]
https://github.com/minexew/Shrine/pull/16
